[package]
name = "cheers"
version = "0.2.0"
authors = ["Sebastian Venter <sebastian.venter@gmail.com>"]
edition = "2021"
default-run = "cheers"

[[bin]]
name = "cheers"
path = "src/main.rs"

[dependencies.cheers_lib]
path = "../cheers_lib"

