[package]
name = "cheers"
version = "0.3.0"
authors = ["Algorhythm"]
edition = "2021"
default-run = "cheers"

[[bin]]
name = "cheers"
path = "src/main.rs"

[dependencies.cheers_lib]
path = "../cheers_lib"

